### ISSUE TITLE
Implement syntax for restricted choices

### ISSUE THREAD

**Issue by parisk** [sourcelair/env-spec-js#4]
env-spec-js should support restricting the available values of an environment variable.

### Input

```
DEBUG: [0,1]
```

### Output

```html
<label for="env_spec_debug">DEBUG</label>
<select id="env_spec_debug" name="debug">
  <option value="0">0</option>
  <option value="1">1</option>
</select>
```

## Spec
https://github.com/sourcelair/env-spec#restricted-choices

**Comment by akanellop** [comment]
I have three questions.
This concerns only the 4 environment variables ADMIN_EMAIL, DATABASE_URL, DEBUG,
ENVIRONMENT?
For any other environment variable we will use just the type?
For the environment variable DATABASE_URL which are the options exactly?

**Comment by parisk** [comment]
> This concerns only the 4 environment variables ADMIN_EMAIL, DATABASE_URL, DEBUG,
ENVIRONMENT?

Nope. This concerns every environment variable that the author of an `.env.spec` file wants to restrict to particular values. So, no hardcoded variable names are needed here.

> For any other environment variable we will use just the type?

The author of an `.env.spec` file can either use a typed environment variable or one with restricted values (or none!). So both of the following lines are valid syntax

```
DEBUG
DEBUG: number
DEBUG: [0,1]
```

**Comment by parisk** [comment]
I forgot one 😅.

> For the environment variable DATABASE_URL which are the options exactly?

All environment variables have the same options, regardless of their names.

We do not have any control on the environment variable names, since they are chosen solely by the author of each `.env.spec` file. `DATABASE_URL` happens to be one of the names we use internally in the company.

**Comment by parisk** [comment]
Closed in https://github.com/sourcelair/env-spec-js/pull/17
