### ISSUE TITLE
Implement a demo page to test env-spec-js in the browser

### ISSUE THREAD

**Issue by parisk** [sourcelair/env-spec-js#8]
We should implement a demo page in order to test env-spec-js easily in a web browser.

What I would expect from it is the following:

1. Typing/Pasting `.env.spec` input
2. Viewing the validity and output HTML code of each `.env.spec` input
3. Viewing the corresponding HTML form rendered into the UI

**Comment by akanellop** [comment]
So for this step, we need to give an input e.g a keyboard input or a file input and we need to open our HTML output with a browser.
Is the ouput going to be a text file which we will open manually with a browser or our program must open the browser by itself?

**Comment by akanellop** [comment]
Are we going to write a new HTLM file for this test page or it is just going to be theHTML output we already have?

**Comment by parisk** [comment]
@akanellop let me share a richer spec about the implementation of this issue and then I will respond to your questions as well 😁.

---

## Spec

### Goal

We need a single HTML page that will let people try out `env-spec-js` by submitting input and receiving the corresponding output.

### User flow

1. The user opens the HTML file in their browser
2. The user types (or pastes) text in `.env.spec` format into a textarea
3. The user presses a button with text **Render**
4. The user views the output HTML text inside  `div` element
5. The user views the actual, visual HTML form corresponding to the output HTML text inside another `div` element

### Demo page contents

1. A `textarea` element that will let users type (or paste) input in `.env.spec` format
2. A `button` element to trigger the rendering
3. A `pre` element that will display the output HTML text
4. A `div` element in which we will render the output HTML (set the `innerHTML` to the output HTML) 

### Tech specs

- The HTML file should be named `index.html` and should be placed in the root directory of the repository
- The HTML file should load the `env_spec.js`
- The HTML file should contain a `script` element that will implement the user interaction (handle button clicks, render the text into HTML etc.)
- We should use `browserify` to make `env_spec.js` work in the browser
- We should use `browser-sync` to serve `index.html` to the browser

### Example

We have already implemented this for `sourcelair/fs-api-js`. Take a look at the following for some hints:

- [`index.html` file](https://github.com/sourcelair/fs-api-js/blob/master/index.html)
- [Launching `browser-sync` with `yarn start`](https://github.com/sourcelair/fs-api-js/blob/master/package.json#L20)
- [Using `browserify`/`watchify` to output browser-compatible script in real-time as we update the original file](https://github.com/sourcelair/fs-api-js/blob/master/package.json#L19)
- [Ignoring the `dist` directory from Git, which contains the browser-compatible JavaScript file](https://github.com/sourcelair/fs-api-js/blob/master/.gitignore#L2)

---

## QnA

> So for this step, we need to give an input e.g a keyboard input or a file input and we need to open our HTML output with a browser.

We need an HTML page that will use `env-spec-js` to accept text input in `.env.spec` format and display the HTML output to the user.

> Is the ouput going to be a text file which we will open manually with a browser or our program must open the browser by itself?

All input/output interactions will happen in the browser.

> Are we going to write a new HTLM file for this test page or it is just going to be theHTML output we already have?

Yes, we will write a new HTML file that will load and use `env-spec-js`.

**Comment by parisk** [comment]
Closed in https://github.com/sourcelair/env-spec-js/pull/12
